# 1.Create a null vector of size 10 but the fifth value which is 1.

In [2]:
import numpy as np

n = np.zeros(10)
n[4] = 1
print(n)


[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


# 2. Create a vector with values ranging from 10 to 49.

In [3]:
n = np.arange(10,50)
n

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

# 3. Create a 3x3 matrix with values ranging from 0 to 8

In [9]:
a = np.array([[[0,1,2],[3,4,5],[6,7,8]]])
print(a)
print(a.ndim)

# or 

n = np.arange(0,9)
matrix = n.reshape(3,3)
print(matrix)
print(matrix.ndim)

[[[0 1 2]
  [3 4 5]
  [6 7 8]]]
3
[[0 1 2]
 [3 4 5]
 [6 7 8]]
2


# 4. Find indices of non-zero elements from [1,2,0,0,4,0]

In [22]:
n = [1,2,0,0,4,0]
a = np.array(n)
i = np.where(a != 0)
print(i)


(array([0, 1, 4], dtype=int64),)


# 5.Create a 10x10 array with random values and find the minimum and maximum values.

In [21]:
ran = np.random.rand(10,1,10)
print(ran)
print('ndimenstions = ', ran.ndim)
print("max values is : ", np.max(ran))
print("min values is : ", np.min(ran))

[[[0.8108302  0.44052823 0.57934635 0.09844476 0.10158648 0.59206777
   0.78389947 0.66380395 0.77091659 0.96089727]]

 [[0.69608676 0.19383733 0.38056661 0.99886748 0.02372072 0.1408305
   0.59795962 0.34579983 0.74265139 0.13992576]]

 [[0.69348331 0.4817277  0.49798082 0.01199625 0.23531517 0.55396011
   0.57357723 0.51073633 0.56348955 0.55332698]]

 [[0.17052621 0.30985489 0.39391401 0.3255643  0.86239892 0.35748078
   0.4502342  0.62303655 0.92618209 0.85084833]]

 [[0.13721799 0.12683674 0.4639446  0.24971058 0.27652866 0.98620708
   0.68431504 0.09412669 0.61904309 0.51902434]]

 [[0.52882106 0.02147254 0.22044173 0.96778464 0.25950041 0.37718715
   0.24227078 0.18674604 0.17539012 0.10615581]]

 [[0.31072428 0.2226517  0.97292272 0.75317618 0.43064155 0.55891071
   0.85555085 0.63867974 0.70758194 0.49217118]]

 [[0.65709944 0.05323609 0.77331711 0.03795444 0.16747156 0.72738793
   0.27455351 0.761185   0.96586065 0.67762224]]

 [[0.9662328  0.01020092 0.34358069 0.4293103  0.

# 6. Create a random vector of size 30 and find the mean value.

In [27]:
n = np.random.randint(100,200,30)
print(n)
m = np.mean(n)
print("mean value is : ",m)

[148 181 144 176 185 182 154 167 150 108 193 152 120 130 133 180 169 164
 139 170 148 124 150 180 164 112 180 174 142 190]
mean value is :  156.96666666666667
