# 1.Create a null vector of size 10 but the fifth value which is 1.

In [5]:
import numpy as np

n = np.zeros(10)
n[4] = 1
print(n)


[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


# 2. Create a vector with values ranging from 10 to 49.

In [6]:
n = np.arange(10,50)
n

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

# 3. Create a 3x3 matrix with values ranging from 0 to 8

In [10]:
n = np.arange(0,9)
matrix = n.reshape(3,3)
matrix

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

# 4. Find indices of non-zero elements from [1,2,0,0,4,0]

In [11]:
n = [1,2,0,0,4,0]
a = np.array(n)
i = np.where(a != 0)
i


(array([0, 1, 4], dtype=int64),)

# 5.Create a 10x10 array with random values and find the minimum and maximum values.

In [21]:
ran = np.random.rand(10,10)
print("max values is : ", np.max(ran))
print("min values is : ", np.min(ran))

max values is :  0.982852487716025
min values is :  0.0011971890587495482


# 6. Create a random vector of size 30 and find the mean value.

In [27]:
n = np.random.randint(100,200,30)
print(n)
m = np.mean(n)
print("mean value is : ",m)

[148 181 144 176 185 182 154 167 150 108 193 152 120 130 133 180 169 164
 139 170 148 124 150 180 164 112 180 174 142 190]
mean value is :  156.96666666666667
